apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepython
  labels:
    app: kubepython
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubepython
  template:
    metadata:
      labels:
        app: kubepython
    spec:
      containers:
      - name: python-app
        image: cruiser7/python-sample-app-wireshark:v1
        ports:
        - containerPort: 8000
