apiVersion: v1
kind: Service
metadata:
  name: kubepython-service
spec:
    type: NodePort
    selector:
        app: kubepython
    ports:
      - port: 80
        targetPort: 8000
        nodePort: 30007